version: '3.8'
services: #Jenkins, SonarQube
  jenkins:
    build:
      context: ./jenkins
      dockerfile: Dockerfile
    image: devsecops-jenkins:lts
    container_name: jenkins
    privileged: true
    ports:
      - "8080:8080"
      - "50000:50000"
    volumes:
      - jenkins_home:/var/jenkins_home
      - /var/lib/docker:/var/lib/docker
    environment:
      - DOCKER_HOST=unix:///var/run/docker.sock
    dns:
      - 8.8.8.8
      - 1.1.1.1
    cap_add:
      - NET_ADMIN  # For iptables in Docker daemon
      - SYS_ADMIN
    networks:
      - jenkins-sonar

  sonarqube:
    image: sonarqube:lts-community
    container_name: sonarqube
    ports:
      - "9000:9000"
    environment:
      SONAR_ES_BOOTSTRAP_CHECKS_DISABLE: "true"
    volumes:
      - sonar_data:/opt/sonarqube/data
    dns:
      - 8.8.8.8
      - 1.1.1.1
    networks:
      - jenkins-sonar

volumes:
  jenkins_home:
  sonar_data:

networks:
  jenkins-sonar:
    driver: bridge